/*
 *  CrimeTrack Database. Seeded from City of Chicago Crimes 2001 to Present
 */
USE crime_s18;

# Import dataset into temporary table to seed real tables
CREATE TABLE temp_import_dataset (
	ID VARCHAR(255) NOT NULL,
	CASE_NUMBER VARCHAR(255) NOT NULL,
	DATE VARCHAR(255) NOT NULL,
	BLOCK VARCHAR(255) NOT NULL,
	IUCR VARCHAR(255) NOT NULL,
	PRIMARY_TYPE VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	LOCATION_DESCRIPTION VARCHAR(255) NOT NULL,
	ARREST VARCHAR(255) NOT NULL,
	DOMESTIC VARCHAR(255) NOT NULL,
	BEAT VARCHAR(255) NOT NULL,
	DISTRICT VARCHAR(255) NOT NULL,
	WARD VARCHAR(255) NOT NULL,
	COMMUNITY_AREA VARCHAR(255) NOT NULL,
	FBI_CODE VARCHAR(255) NOT NULL,
	X_COORDINATE VARCHAR(255) NOT NULL,
	Y_COORDINATE VARCHAR(255) NOT NULL,
	YEAR VARCHAR(255) NOT NULL,
	UPDATED_ON VARCHAR(255) NOT NULL,
	LATITUDE VARCHAR(255) NOT NULL,
	LONGITUDE VARCHAR(255) NOT NULL,
	LOCATION VARCHAR(255) NOT NULL );

# LOAD DATA LOCAL INFILE "Crimes_-_2001_to_present.csv"  INTO TABLE temp_import_dataset IGNORE 1;

CREATE TABLE crimetrack_location_types (
	location_ID INT(11) AUTO_INCREMENT NOT NULL,
	location_desc VARCHAR(255)  NOT NULL,
	PRIMARY KEY(location_ID)
)

CREATE TABLE crimetrack_crime_type (
	IUCR_PK SMALLINT NOT NULL,
	crime_type VARCHAR(255) NOT NULL,
	crime_description VARCHARR(255) NOT NULL,
	PRIMARY KEY(IUCR_PK)
)

CREATE TABLE crimetrack_chicago_community_areas (
	area_id SMALLINT NOT NULL,
	community_name VARCHAR(255),
	population VARCHAR(255),
	income VARCHAR(255)
)
