version: '2.1'

services:
 crimetrack-php:
  build: ./Application
  restart: always
  volumes:
    - ./Application/src:/var/www/html
  ports:
   - 80:80
    
 crimetrack-database:
  restart: always
  build: ./Database
  ports:
   - 3306:3306
  volumes:
   - crimetrack-db:/var/lib/mysql

 crimetrack-phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  environment:
   - PMA_HOST=crimetrack-database
  ports:
   - 8080:80

volumes:
 crimetrack-db:
